### ISSUE TITLE
ClientGroup not available

### ISSUE THREAD

**Issue by tonyhogsten** [CommvaultEngg/ansible#2]
According to the documentation we are able to use clientgroup, but when attempting to use it

```yaml
entity_type: clientgroup
```
it's not available

`The error was: NameError: name 'clientgroup' is not defined`

**Comment by spakhare** [comment]
Hi @tonyhogsten,

Can you please point us to the function you are referring to here? 

Thanks,
Sachin

**Comment by tonyhogsten** [comment]
Haven't tried using a specific function as the class clientgroup cannot be instantiated with the ansible module as there is no support for it as I can see in the code. 

```yaml
- name: get all client groups within the commcell
  commvault:
    commcell: "{{ commcell }}"
    operation: "_get_clientgroups"
    entity_type: clientgroup
    entity: {
      clientgroup: "_Avvecklade"
    }
  register: clientgroups

- name: debug clients
  debug:
    var: clientgroups
```
Generated the error I wrote, `The error was: NameError: name 'clientgroup' is not defined`

I've made changes to the commvault.py code locally, added 

```python
Line 243  global commcell, client, clients, agent, agents, instance, instances, backupset, backupsets, subclient, subclients, result, clientgroup, clientgroups


    if 'clientgroup' in entity:
        clientgroups = commcell_object.client_groups
        clientgroup = clientgroups.get(entity['clientgroup'])   
```
And this worked and retrieved all clientgroups. Is this a miss in the original code? As you wrote entity_type with the value clientgroups was supported?
